version: 0.2

phases:
  install:
    runtime-versions:
      java: jdk1.8.0_192
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - **/*.jar
    
  discard-paths: yes
